Repository crispindeity/warming-up-study-mini, pull requests merged in 2024-03, with the labels that each got.

#5 Yeong-Huns_1일차
  Yeong-Huns/.gitignore
  Yeong-Huns/build.gradle
  Yeong-Huns/gradle/wrapper/gradle-wrapper.jar
  Yeong-Huns/gradle/wrapper/gradle-wrapper.properties
  Yeong-Huns/gradlew
  Yeong-Huns/gradlew.bat
  Yeong-Huns/settings.gradle
  Yeong-Huns/src/main/java/org/example/yeonghuns/YeongHunsApplication.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/controller/MemberController.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/controller/TeamController.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/domain/Member.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/domain/Team.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/dto/member/request/SaveMemberRequest.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/dto/member/response/GetAllMembersResponse.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/dto/team/request/CreateTeamRequest.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/dto/team/response/GetAllTeamsResponse.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/repository/MemberRepository.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/repository/TeamRepository.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/service/member/MemberService.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/service/team/TeamService.java
  Yeong-Huns/src/main/resources/application.yml
  Yeong-Huns/src/test/java/org/example/yeonghuns/YeongHunsApplicationTests.java
Labels: 1️⃣ 1단계

#6 1단계 제출합니다.
  leeedohyun/.gitignore
  leeedohyun/build.gradle
  leeedohyun/gradle/wrapper/gradle-wrapper.jar
  leeedohyun/gradle/wrapper/gradle-wrapper.properties
  leeedohyun/gradlew
  leeedohyun/gradlew.bat
  leeedohyun/settings.gradle
  leeedohyun/src/main/java/inflearn/mini/MiniApplication.java
  leeedohyun/src/main/java/inflearn/mini/employee/controller/EmployeeController.java
  leeedohyun/src/main/java/inflearn/mini/employee/domain/Employee.java
  leeedohyun/src/main/java/inflearn/mini/employee/domain/Role.java
  leeedohyun/src/main/java/inflearn/mini/employee/dto/request/EmployeeRegisterRequestDto.java
  leeedohyun/src/main/java/inflearn/mini/employee/dto/response/EmployeeResponse.java
  leeedohyun/src/main/java/inflearn/mini/employee/repository/EmployeeRepository.java
  leeedohyun/src/main/java/inflearn/mini/employee/service/EmployeeService.java
  leeedohyun/src/main/java/inflearn/mini/global/ExceptionResponse.java
  leeedohyun/src/main/java/inflearn/mini/global/GlobalExceptionHandler.java
  leeedohyun/src/main/java/inflearn/mini/team/controller/TeamController.java
  leeedohyun/src/main/java/inflearn/mini/team/domain/Team.java
  leeedohyun/src/main/java/inflearn/mini/team/dto/request/TeamRegisterRequestDto.java
  leeedohyun/src/main/java/inflearn/mini/team/dto/response/TeamResponseDto.java
  leeedohyun/src/main/java/inflearn/mini/team/exception/TeamAlreadyExistException.java
  leeedohyun/src/main/java/inflearn/mini/team/exception/TeamNotFoundException.java
  leeedohyun/src/main/java/inflearn/mini/team/repository/TeamRepository.java
  leeedohyun/src/main/java/inflearn/mini/team/service/TeamService.java
  leeedohyun/src/main/resources/application.yml
  leeedohyun/src/test/java/inflearn/mini/MiniApplicationTests.java
  leeedohyun/src/test/java/inflearn/mini/api/ApiTest.java
  leeedohyun/src/test/java/inflearn/mini/api/DatabaseCleanUp.java
  leeedohyun/src/test/java/inflearn/mini/api/EmployeeApiTest.java
  leeedohyun/src/test/java/inflearn/mini/api/TeamApiTest.java
  leeedohyun/src/test/java/inflearn/mini/api/steps/EmployeeSteps.java
  leeedohyun/src/test/java/inflearn/mini/api/steps/TeamSteps.java
  leeedohyun/src/test/java/inflearn/mini/employee/controller/EmployeeControllerTest.java
  leeedohyun/src/test/java/inflearn/mini/employee/domain/EmployeeTest.java
  leeedohyun/src/test/java/inflearn/mini/employee/service/EmployeeServiceTest.java
  leeedohyun/src/test/java/inflearn/mini/team/controller/TeamControllerTest.java
  leeedohyun/src/test/java/inflearn/mini/team/domain/TeamTest.java
  leeedohyun/src/test/java/inflearn/mini/team/service/TeamServiceTest.java
Labels: 1️⃣ 1단계

#8 [step1] 미니프로젝트 1단계 과제 제출.
  sungbin/mini/build.gradle
  sungbin/mini/src/main/java/me/sungbin/domain/member/controller/EmployeeController.java
  sungbin/mini/src/main/java/me/sungbin/domain/member/entity/Employee.java
  sungbin/mini/src/main/java/me/sungbin/domain/member/model/FindEmployeesInfoResponseDto.java
  sungbin/mini/src/main/java/me/sungbin/domain/member/model/request/RegisterEmployeeRequestDto.java
  sungbin/mini/src/main/java/me/sungbin/domain/member/repository/EmployeeRepository.java
  sungbin/mini/src/main/java/me/sungbin/domain/member/service/EmployeeService.java
  sungbin/mini/src/main/java/me/sungbin/domain/member/type/Role.java
  sungbin/mini/src/main/java/me/sungbin/domain/team/controller/TeamController.java
  sungbin/mini/src/main/java/me/sungbin/domain/team/entity/Team.java
  sungbin/mini/src/main/java/me/sungbin/domain/team/model/request/RegisterTeamRequestDto.java
  sungbin/mini/src/main/java/me/sungbin/domain/team/model/response/FindTeamInfoResponseDto.java
  sungbin/mini/src/main/java/me/sungbin/domain/team/repository/TeamRepository.java
  sungbin/mini/src/main/java/me/sungbin/domain/team/service/TeamService.java
  sungbin/mini/src/main/java/me/sungbin/global/common/entity/BaseDateTimeEntity.java
  sungbin/mini/src/main/java/me/sungbin/global/common/entity/BaseEntity.java
  sungbin/mini/src/main/java/me/sungbin/global/common/type/EnumType.java
  sungbin/mini/src/main/java/me/sungbin/global/config/audit/AuditConfig.java
  sungbin/mini/src/main/java/me/sungbin/global/config/audit/AuditorAwareImpl.java
  sungbin/mini/src/main/java/me/sungbin/global/exception/ExceptionCode.java
  sungbin/mini/src/main/java/me/sungbin/global/exception/ExceptionResponse.java
  sungbin/mini/src/main/java/me/sungbin/global/exception/GlobalExceptionCode.java
  sungbin/mini/src/main/java/me/sungbin/global/exception/GlobalExceptionHandler.java
  sungbin/mini/src/main/java/me/sungbin/global/exception/ValidationException.java
  sungbin/mini/src/main/java/me/sungbin/global/exception/custom/AlreadyExistsManagerException.java
  sungbin/mini/src/main/java/me/sungbin/global/exception/custom/TeamAlreadyExistsException.java
  sungbin/mini/src/main/java/me/sungbin/global/exception/custom/TeamNotFoundException.java
  sungbin/mini/src/main/resources/application.properties
  sungbin/mini/src/main/resources/application.yml
  sungbin/mini/src/test/java/me/sungbin/AppTests.java
  sungbin/mini/src/test/java/me/sungbin/domain/member/controller/EmployeeControllerTest.java
  sungbin/mini/src/test/java/me/sungbin/domain/member/service/EmployeeServiceTest.java
  sungbin/mini/src/test/java/me/sungbin/domain/team/controller/TeamControllerTest.java
  sungbin/mini/src/test/java/me/sungbin/global/common/annotation/IntegrationTest.java
  sungbin/mini/src/test/java/me/sungbin/global/common/controller/BaseControllerTest.java
  sungbin/mini/src/test/resources/application.yml
Labels: 1️⃣ 1단계

#7 1단계 개발. 테스트코드 X
  chaewon/.gitignore
  chaewon/build.gradle
  chaewon/src/main/java/com/miniproject/commute/controller/member/MemberController.java
  chaewon/src/main/java/com/miniproject/commute/controller/team/TeamController.java
  chaewon/src/main/java/com/miniproject/commute/domain/Member.java
  chaewon/src/main/java/com/miniproject/commute/domain/Role.java
  chaewon/src/main/java/com/miniproject/commute/domain/Team.java
  chaewon/src/main/java/com/miniproject/commute/dto/member/request/ChooseManagerRequest.java
  chaewon/src/main/java/com/miniproject/commute/dto/member/request/MemberSaveRequest.java
  chaewon/src/main/java/com/miniproject/commute/dto/member/response/MemberResponse.java
  chaewon/src/main/java/com/miniproject/commute/dto/team/request/TeamSaveRequest.java
  chaewon/src/main/java/com/miniproject/commute/dto/team/response/TeamGetResponse.java
  chaewon/src/main/java/com/miniproject/commute/dto/team/response/TeamMemberCountResponse.java
  chaewon/src/main/java/com/miniproject/commute/repository/member/MemberRepository.java
  chaewon/src/main/java/com/miniproject/commute/repository/team/TeamRepository.java
  chaewon/src/main/java/com/miniproject/commute/service/member/MemberService.java
  chaewon/src/main/java/com/miniproject/commute/service/team/TeamService.java
  chaewon/src/main/resources/application.properties
Labels: 1️⃣ 1단계

#10 1단계: 미니 프로젝트 1단계 요구사항 구현
  crispin/README.md
  crispin/build.gradle
  crispin/http/request.http
  crispin/src/main/java/study/crispin/common/exception/ExceptionControllerAdvice.java
  crispin/src/main/java/study/crispin/member/application/request/MemberRegistrationRequest.java
  crispin/src/main/java/study/crispin/member/application/request/MemberUpdateRequest.java
  crispin/src/main/java/study/crispin/member/application/service/MemberService.java
  crispin/src/main/java/study/crispin/member/application/service/MemberServiceImpl.java
  crispin/src/main/java/study/crispin/member/domain/Member.java
  crispin/src/main/java/study/crispin/member/domain/Role.java
  crispin/src/main/java/study/crispin/member/infrastructure/entity/MemberEntity.java
  crispin/src/main/java/study/crispin/member/infrastructure/repository/JpaMemberRepository.java
  crispin/src/main/java/study/crispin/member/infrastructure/repository/MemberRepository.java
  crispin/src/main/java/study/crispin/member/infrastructure/repository/MemberRepositoryImpl.java
  crispin/src/main/java/study/crispin/member/presentation/controller/MemberController.java
  crispin/src/main/java/study/crispin/member/presentation/response/MemberRegistrationResponse.java
  crispin/src/main/java/study/crispin/member/presentation/response/MemberRetrieveResponse.java
  crispin/src/main/java/study/crispin/member/presentation/response/MemberRetrieveResponses.java
  crispin/src/main/java/study/crispin/member/presentation/response/MemberUpdateResponse.java
  crispin/src/main/java/study/crispin/team/application/request/TeamRegistrationRequest.java
  crispin/src/main/java/study/crispin/team/application/service/TeamService.java
  crispin/src/main/java/study/crispin/team/application/service/TeamServiceImpl.java
  crispin/src/main/java/study/crispin/team/domain/Team.java
  crispin/src/main/java/study/crispin/team/infrastructure/entity/TeamEntity.java
  crispin/src/main/java/study/crispin/team/infrastructure/repository/JpaTeamRepository.java
  crispin/src/main/java/study/crispin/team/infrastructure/repository/TeamRepository.java
  crispin/src/main/java/study/crispin/team/infrastructure/repository/TeamRepositoryImpl.java
  crispin/src/main/java/study/crispin/team/presentation/controller/TeamController.java
  crispin/src/main/java/study/crispin/team/presentation/response/TeamRegistrationResponse.java
  crispin/src/main/java/study/crispin/team/presentation/response/TeamRetrieveResponse.java
  crispin/src/main/java/study/crispin/team/presentation/response/TeamRetrieveResponses.java
  crispin/src/main/resources/application.yml
  crispin/src/main/resources/schema.sql
  crispin/src/test/java/study/crispin/ApiTest.java
  crispin/src/test/java/study/crispin/DatabaseCleanup.java
  crispin/src/test/java/study/crispin/fixture/TestMemberFixture.java
  crispin/src/test/java/study/crispin/fixture/TestTeamFixture.java
  crispin/src/test/java/study/crispin/member/MemberControllerTest.java
  crispin/src/test/java/study/crispin/member/MemberIntegrationTest.java
  crispin/src/test/java/study/crispin/member/MemberServiceTest.java
  crispin/src/test/java/study/crispin/mock/FakeMemberRepository.java
  crispin/src/test/java/study/crispin/mock/FakeTeamRepository.java
  crispin/src/test/java/study/crispin/steps/MemberSteps.java
  crispin/src/test/java/study/crispin/steps/TeamSteps.java
  crispin/src/test/java/study/crispin/team/TeamControllerTest.java
  crispin/src/test/java/study/crispin/team/TeamIntegrationTest.java
  crispin/src/test/java/study/crispin/team/TeamServiceTest.java
Labels: 1️⃣ 1단계

#14 2단계 기능 개발
  chaewon/build.gradle
  chaewon/src/main/java/com/miniproject/commute/controller/commute/CommuteController.java
  chaewon/src/main/java/com/miniproject/commute/controller/member/MemberController.java
  chaewon/src/main/java/com/miniproject/commute/controller/team/TeamController.java
  chaewon/src/main/java/com/miniproject/commute/controller/workingTime/WorkingTimeController.java
  chaewon/src/main/java/com/miniproject/commute/domain/Commute.java
  chaewon/src/main/java/com/miniproject/commute/domain/Member.java
  chaewon/src/main/java/com/miniproject/commute/domain/Team.java
  chaewon/src/main/java/com/miniproject/commute/domain/WorkingTime.java
  chaewon/src/main/java/com/miniproject/commute/domain/WorkingTimePK.java
  chaewon/src/main/java/com/miniproject/commute/dto/commute/request/WorkInRequest.java
  chaewon/src/main/java/com/miniproject/commute/dto/commute/request/WorkOutRequest.java
  chaewon/src/main/java/com/miniproject/commute/dto/member/request/ChooseManagerRequest.java
  chaewon/src/main/java/com/miniproject/commute/dto/member/request/MemberSaveRequest.java
  chaewon/src/main/java/com/miniproject/commute/dto/member/response/MemberResponse.java
  chaewon/src/main/java/com/miniproject/commute/dto/team/request/TeamSaveRequest.java
  chaewon/src/main/java/com/miniproject/commute/dto/workingTime/request/DayOffApplicationRequest.java
  chaewon/src/main/java/com/miniproject/commute/dto/workingTime/request/WorkingTimeRequest.java
  chaewon/src/main/java/com/miniproject/commute/dto/workingTime/response/WorkingTimeResponse.java
  chaewon/src/main/java/com/miniproject/commute/dto/workingTime/response/WorkingTimeResponseDetail.java
  chaewon/src/main/java/com/miniproject/commute/repository/commute/CommuteRepository.java
  chaewon/src/main/java/com/miniproject/commute/repository/member/MemberRepository.java
  chaewon/src/main/java/com/miniproject/commute/repository/workingTime/WorkingTimeRepository.java
  chaewon/src/main/java/com/miniproject/commute/service/commute/CommuteService.java
  chaewon/src/main/java/com/miniproject/commute/service/member/MemberService.java
  chaewon/src/main/java/com/miniproject/commute/service/team/TeamService.java
  chaewon/src/main/java/com/miniproject/commute/service/workingTime/WorkingTimeService.java
Labels: 2️⃣ 2단계

#13 [step3] 미니프로젝트 3단계 기능 개발 완료
  sungbin/mini/src/main/java/me/sungbin/domain/annual/controller/AnnualLeaveController.java
  sungbin/mini/src/main/java/me/sungbin/domain/annual/entity/AnnualLeave.java
  sungbin/mini/src/main/java/me/sungbin/domain/annual/model/request/AnnualLeaveRequestDto.java
  sungbin/mini/src/main/java/me/sungbin/domain/annual/model/response/AnnualLeaveResponseDto.java
  sungbin/mini/src/main/java/me/sungbin/domain/annual/repository/AnnualLeaveRepository.java
  sungbin/mini/src/main/java/me/sungbin/domain/annual/service/AnnualLeaveService.java
  sungbin/mini/src/main/java/me/sungbin/domain/attendance/model/response/WorkTimeDetail.java
  sungbin/mini/src/main/java/me/sungbin/domain/attendance/service/AttendanceService.java
  sungbin/mini/src/main/java/me/sungbin/domain/employee/entity/Employee.java
  sungbin/mini/src/main/java/me/sungbin/domain/employee/service/EmployeeService.java
  sungbin/mini/src/main/java/me/sungbin/domain/team/entity/Team.java
  sungbin/mini/src/main/java/me/sungbin/domain/team/model/request/RegistrationTeamRequestDto.java
  sungbin/mini/src/main/java/me/sungbin/global/exception/GlobalExceptionHandler.java
  sungbin/mini/src/main/java/me/sungbin/global/exception/custom/AnnualLeaveException.java
  sungbin/mini/src/test/java/me/sungbin/domain/annual/controller/AnnualLeaveControllerTest.java
  sungbin/mini/src/test/java/me/sungbin/domain/attendance/controller/AttendanceControllerTest.java
  sungbin/mini/src/test/java/me/sungbin/domain/employee/controller/EmployeeControllerTest.java
  sungbin/mini/src/test/java/me/sungbin/domain/employee/service/EmployeeServiceTest.java
  sungbin/mini/src/test/java/me/sungbin/domain/team/controller/TeamControllerTest.java
Labels: 3️⃣ 3단계

#12 Step 02
  Yeong-Huns/build.gradle
  Yeong-Huns/src/main/java/org/example/yeonghuns/YeongHunsApplication.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/common/BaseEntity.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/common/CreatedDateEntity.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/config/Error/ErrorCode.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/config/Error/ErrorResponse.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/config/Error/GlobalExceptionHandler.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/config/Error/exception/BadRequestException.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/config/Error/exception/CustomBaseException.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/config/Error/exception/NotFoundException.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/config/Error/exception/commute/AbsentCheckOutException.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/config/Error/exception/commute/AlreadyAttendanceException.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/config/Error/exception/commute/AlreadyDepartureException.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/config/Error/exception/commute/CommuteNotFoundException.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/config/Error/exception/member/MemberNotFoundException.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/config/Error/exception/team/TeamAlreadyExistsException.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/config/Error/exception/team/TeamNotFoundException.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/config/audit/AuditConfig.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/controller/CommuteController.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/domain/Commute.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/domain/Member.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/domain/Team.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/dto/commute/request/EndOfWorkRequest.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/dto/commute/request/GetCommuteRecordRequest.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/dto/commute/request/StartOfWorkRequest.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/dto/commute/response/GetCommuteDetail.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/dto/commute/response/GetCommuteRecordResponse.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/dto/member/response/GetAllMembersResponse.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/dto/team/response/GetAllTeamsResponse.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/repository/CommuteRepository.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/service/commute/CommuteService.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/service/team/TeamService.java
  Yeong-Huns/src/main/resources/application.yml
Labels: 2️⃣ 2단계

#11 2단계 제출합니다.
  leeedohyun/src/main/java/inflearn/mini/employee/controller/EmployeeController.java
  leeedohyun/src/main/java/inflearn/mini/employee/domain/Employee.java
  leeedohyun/src/main/java/inflearn/mini/employee/dto/request/EmployeeWorkHistoryRequest.java
  leeedohyun/src/main/java/inflearn/mini/employee/dto/response/DateWorkMinutes.java
  leeedohyun/src/main/java/inflearn/mini/employee/dto/response/EmployeeWorkHistoryResponse.java
  leeedohyun/src/main/java/inflearn/mini/employee/exception/AbsentEmployeeException.java
  leeedohyun/src/main/java/inflearn/mini/employee/exception/AlreadyAtWorkException.java
  leeedohyun/src/main/java/inflearn/mini/employee/exception/AlreadyLeftException.java
  leeedohyun/src/main/java/inflearn/mini/employee/exception/EmployeeNotFoundException.java
  leeedohyun/src/main/java/inflearn/mini/employee/repository/EmployeeRepository.java
  leeedohyun/src/main/java/inflearn/mini/global/BadRequestException.java
  leeedohyun/src/main/java/inflearn/mini/global/GlobalExceptionHandler.java
  leeedohyun/src/main/java/inflearn/mini/global/NotFoundException.java
  leeedohyun/src/main/java/inflearn/mini/team/exception/TeamAlreadyExistException.java
  leeedohyun/src/main/java/inflearn/mini/team/exception/TeamNotFoundException.java
  leeedohyun/src/main/java/inflearn/mini/worktimehistory/domain/WorkTimeHistory.java
  leeedohyun/src/main/java/inflearn/mini/worktimehistory/repsoitory/WorkTimeHistoryRepository.java
  leeedohyun/src/main/java/inflearn/mini/worktimehistory/service/WorkTimeHistoryService.java
  leeedohyun/src/test/java/inflearn/mini/api/EmployeeApiTest.java
  leeedohyun/src/test/java/inflearn/mini/api/steps/EmployeeSteps.java
  leeedohyun/src/test/java/inflearn/mini/employee/controller/EmployeeControllerTest.java
  leeedohyun/src/test/java/inflearn/mini/worktimehistory/domain/WorkTimeHistoryTest.java
  leeedohyun/src/test/java/inflearn/mini/worktimehistory/service/WorkTimeHistoryServiceTest.java
Labels: 2️⃣ 2단계

#16 2단계: 미니 프로젝트 2단계 요구사항 구현
  crispin/README.md
  crispin/http/request.http
  crispin/src/main/java/study/crispin/attendance/application/AttendanceService.java
  crispin/src/main/java/study/crispin/attendance/application/AttendanceServiceImpl.java
  crispin/src/main/java/study/crispin/attendance/application/request/ClockInOrOutRequest.java
  crispin/src/main/java/study/crispin/attendance/application/request/WorkHoursInquiryRequest.java
  crispin/src/main/java/study/crispin/attendance/domain/Attendance.java
  crispin/src/main/java/study/crispin/attendance/infrastructure/entity/AttendanceEntity.java
  crispin/src/main/java/study/crispin/attendance/infrastructure/repository/AttendanceRepository.java
  crispin/src/main/java/study/crispin/attendance/infrastructure/repository/AttendanceRepositoryImpl.java
  crispin/src/main/java/study/crispin/attendance/infrastructure/repository/JpaAttendanceRepository.java
  crispin/src/main/java/study/crispin/attendance/presentation/controller/AttendanceController.java
  crispin/src/main/java/study/crispin/attendance/presentation/response/ClockInResponse.java
  crispin/src/main/java/study/crispin/attendance/presentation/response/ClockOutResponse.java
  crispin/src/main/java/study/crispin/attendance/presentation/response/WorkHoursInquiryResponse.java
  crispin/src/main/java/study/crispin/attendance/presentation/response/WorkHoursInquiryResponses.java
  crispin/src/main/java/study/crispin/common/DateTimeHolder.java
  crispin/src/main/java/study/crispin/common/LocalDateUtil.java
  crispin/src/main/java/study/crispin/common/SystemDateTimeHolder.java
  crispin/src/main/java/study/crispin/common/controller/ExceptionControllerAdvice.java
  crispin/src/main/java/study/crispin/common/controller/response/ExceptionResponse.java
  crispin/src/main/java/study/crispin/common/exception/ApiRequestException.java
  crispin/src/main/java/study/crispin/common/exception/ExceptionControllerAdvice.java
  crispin/src/main/java/study/crispin/common/exception/ExceptionMessage.java
  crispin/src/main/java/study/crispin/common/exception/NotFoundException.java
  crispin/src/main/java/study/crispin/common/exception/VerificationException.java
  crispin/src/main/java/study/crispin/member/application/request/MemberRegistrationRequest.java
  crispin/src/main/java/study/crispin/member/application/request/MemberUpdateRequest.java
  crispin/src/main/java/study/crispin/member/application/service/MemberService.java
  crispin/src/main/java/study/crispin/member/application/service/MemberServiceImpl.java
  crispin/src/main/java/study/crispin/member/domain/Member.java
  crispin/src/main/java/study/crispin/member/infrastructure/repository/JpaMemberRepository.java
  crispin/src/main/java/study/crispin/member/infrastructure/repository/MemberRepository.java
  crispin/src/main/java/study/crispin/member/infrastructure/repository/MemberRepositoryImpl.java
  crispin/src/main/java/study/crispin/member/presentation/controller/MemberController.java
  crispin/src/main/java/study/crispin/member/presentation/response/MemberRegistrationResponse.java
  crispin/src/main/java/study/crispin/team/application/service/TeamServiceImpl.java
  crispin/src/main/java/study/crispin/team/infrastructure/repository/JpaTeamRepository.java
  crispin/src/main/java/study/crispin/team/infrastructure/repository/TeamRepository.java
  crispin/src/main/java/study/crispin/team/infrastructure/repository/TeamRepositoryImpl.java
  crispin/src/main/java/study/crispin/team/presentation/controller/TeamController.java
  crispin/src/main/resources/schema.sql
  crispin/src/test/java/study/crispin/attendance/AttendanceControllerTest.java
  crispin/src/test/java/study/crispin/attendance/AttendanceIntegrationTest.java
  crispin/src/test/java/study/crispin/attendance/AttendanceServiceImplTest.java
  crispin/src/test/java/study/crispin/fixture/TestMemberFixture.java
  crispin/src/test/java/study/crispin/fixture/TestWorkHistoryFixture.java
  crispin/src/test/java/study/crispin/member/MemberControllerTest.java
  crispin/src/test/java/study/crispin/member/MemberIntegrationTest.java
  crispin/src/test/java/study/crispin/member/MemberServiceTest.java
  crispin/src/test/java/study/crispin/mock/FakeAttendanceRepository.java
  crispin/src/test/java/study/crispin/mock/FakeDateTimeHolder.java
  crispin/src/test/java/study/crispin/mock/FakeMemberRepository.java
  crispin/src/test/java/study/crispin/mock/FakeTeamRepository.java
  crispin/src/test/java/study/crispin/steps/AttendanceSteps.java
  crispin/src/test/java/study/crispin/steps/MemberSteps.java
  crispin/src/test/java/study/crispin/steps/TeamSteps.java
  crispin/src/test/java/study/crispin/team/TeamControllerTest.java
  crispin/src/test/java/study/crispin/team/TeamIntegrationTest.java
  crispin/src/test/java/study/crispin/team/TeamServiceTest.java
Labels: 2️⃣ 2단계

#18 미니 프로젝트 Step03
  Yeong-Huns/src/main/java/org/example/yeonghuns/YeongHunsApplication.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/config/Error/ErrorCode.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/config/Error/GlobalExceptionHandler.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/config/Error/exception/annualLeave/AcceptTeamPolicyException.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/config/Error/exception/annualLeave/AlreadyRegisteredException.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/config/Error/exception/annualLeave/BeforeTodayException.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/config/Error/exception/annualLeave/RemainAnnualLeavesException.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/config/Error/exception/commute/UsingAnnualLeavesException.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/controller/AnnualLeaveController.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/controller/TeamController.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/domain/AnnualLeave.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/domain/JoinDate.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/domain/Member.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/domain/Team.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/dto/annualLeave/request/GetRemainAnnualLeavesRequest.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/dto/annualLeave/request/RegisterAnnualLeaveRequest.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/dto/annualLeave/response/GetRemainAnnualLeavesResponse.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/dto/commute/request/GetCommuteRecordRequest.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/dto/commute/response/GetCommuteDetail.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/dto/team/request/CreateTeamRequest.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/dto/team/request/UpdateDayBeforeAnnualRequest.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/repository/AnnualLeaveRepository.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/repository/CommuteRepository.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/service/annual/AnnualLeaveService.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/service/commute/CommuteService.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/service/member/MemberService.java
  Yeong-Huns/src/main/java/org/example/yeonghuns/service/team/TeamService.java
Labels: 3️⃣ 3단계

#17 1단계 개발
  .gitignore
  crispin/settings.gradle
  crispin/src/main/java/study/crispin/CrispinApplication.java
  crispin/src/test/java/study/crispin/CrispinApplicationTests.java
  crispin/src/test/resources/application.properties
  jokim/workHub/.gitignore
  jokim/workHub/build.gradle
  jokim/workHub/gradle/wrapper/gradle-wrapper.jar
  jokim/workHub/gradle/wrapper/gradle-wrapper.properties
  jokim/workHub/gradlew
  jokim/workHub/gradlew.bat
  jokim/workHub/settings.gradle
  jokim/workHub/src/main/java/inflearn/mini/workHub/WorkHubApplication.java
  jokim/workHub/src/main/java/inflearn/mini/workHub/employee/controller/EmployeeController.java
  jokim/workHub/src/main/java/inflearn/mini/workHub/employee/domain/Employee.java
  jokim/workHub/src/main/java/inflearn/mini/workHub/employee/domain/Role.java
  jokim/workHub/src/main/java/inflearn/mini/workHub/employee/dto/EmployeeInfoResponse.java
  jokim/workHub/src/main/java/inflearn/mini/workHub/employee/dto/EmployeeRegisterRequest.java
  jokim/workHub/src/main/java/inflearn/mini/workHub/employee/repository/EmployeeRepository.java
  jokim/workHub/src/main/java/inflearn/mini/workHub/employee/service/EmployeeService.java
  jokim/workHub/src/main/java/inflearn/mini/workHub/global/CustomException.java
  jokim/workHub/src/main/java/inflearn/mini/workHub/global/CustomExceptionHandler.java
  jokim/workHub/src/main/java/inflearn/mini/workHub/global/ErrorCode.java
  jokim/workHub/src/main/java/inflearn/mini/workHub/global/ErrorResponse.java
  jokim/workHub/src/main/java/inflearn/mini/workHub/team/controller/TeamController.java
  jokim/workHub/src/main/java/inflearn/mini/workHub/team/domain/Team.java
  jokim/workHub/src/main/java/inflearn/mini/workHub/team/dto/TeamCreateRequest.java
  jokim/workHub/src/main/java/inflearn/mini/workHub/team/dto/TeamInfoResponse.java
  jokim/workHub/src/main/java/inflearn/mini/workHub/team/repository/TeamRepository.java
  jokim/workHub/src/main/java/inflearn/mini/workHub/team/service/TeamService.java
  jokim/workHub/src/main/resources/application.yml
  jokim/workHub/src/test/java/inflearn/mini/workHub/WorkHubApplicationTests.java
  sungbin/mini/.gitignore
  sungbin/mini/gradle/wrapper/gradle-wrapper.properties
  sungbin/mini/gradlew
  sungbin/mini/gradlew.bat
  sungbin/mini/settings.gradle
  sungbin/mini/src/main/java/me/sungbin/App.java
Labels: 1️⃣ 1단계

#19 3단계 제출합니다
  leeedohyun/build.gradle
  leeedohyun/src/main/java/inflearn/mini/annualleave/controller/AnnualLeaveController.java
  leeedohyun/src/main/java/inflearn/mini/annualleave/domain/AnnualLeave.java
  leeedohyun/src/main/java/inflearn/mini/annualleave/dto/request/AnnualLeaveRequestDto.java
  leeedohyun/src/main/java/inflearn/mini/annualleave/dto/request/RemainingAnnualLeaveRequestDto.java
  leeedohyun/src/main/java/inflearn/mini/annualleave/dto/response/RemainingAnnualLeaveResponseDto.java
  leeedohyun/src/main/java/inflearn/mini/annualleave/exception/ExhaustedAnnualLeaveException.java
  leeedohyun/src/main/java/inflearn/mini/annualleave/exception/InvalidAnnualLeaveRequestException.java
  leeedohyun/src/main/java/inflearn/mini/annualleave/repository/AnnualLeaveRepository.java
  leeedohyun/src/main/java/inflearn/mini/annualleave/service/AnnualLeaveService.java
  leeedohyun/src/main/java/inflearn/mini/commute/controller/CommuteController.java
  leeedohyun/src/main/java/inflearn/mini/commute/domain/Commute.java
  leeedohyun/src/main/java/inflearn/mini/commute/dto/request/CommutingRequestDto.java
  leeedohyun/src/main/java/inflearn/mini/commute/dto/request/EndOfWorkRequestDto.java
  leeedohyun/src/main/java/inflearn/mini/commute/repsoitory/CommuteRepository.java
  leeedohyun/src/main/java/inflearn/mini/commute/service/CommuteService.java
  leeedohyun/src/main/java/inflearn/mini/employee/controller/EmployeeController.java
  leeedohyun/src/main/java/inflearn/mini/employee/domain/Employee.java
  leeedohyun/src/main/java/inflearn/mini/employee/dto/request/EmployeeDailyWorkingHoursRequest.java
  leeedohyun/src/main/java/inflearn/mini/employee/dto/request/EmployeeRegisterRequestDto.java
  leeedohyun/src/main/java/inflearn/mini/employee/dto/request/EmployeeWorkHistoryRequest.java
  leeedohyun/src/main/java/inflearn/mini/employee/dto/response/DateWorkMinutes.java
  leeedohyun/src/main/java/inflearn/mini/employee/dto/response/EmployeeCommuteResponse.java
  leeedohyun/src/main/java/inflearn/mini/employee/dto/response/EmployeeWorkHistoryResponse.java
  leeedohyun/src/main/java/inflearn/mini/employee/repository/EmployeeRepository.java
  leeedohyun/src/main/java/inflearn/mini/global/GlobalExceptionHandler.java
  leeedohyun/src/main/java/inflearn/mini/team/controller/TeamController.java
  leeedohyun/src/main/java/inflearn/mini/team/domain/Team.java
  leeedohyun/src/main/java/inflearn/mini/team/dto/request/TeamRegisterRequestDto.java
  leeedohyun/src/main/java/inflearn/mini/worktimehistory/repsoitory/WorkTimeHistoryRepository.java
  leeedohyun/src/main/java/inflearn/mini/worktimehistory/service/WorkTimeHistoryService.java
  leeedohyun/src/test/java/inflearn/mini/annualleave/controller/AnnualLeaveControllerTest.java
  leeedohyun/src/test/java/inflearn/mini/annualleave/domain/AnnualLeaveTest.java
  leeedohyun/src/test/java/inflearn/mini/annualleave/service/AnnualLeaveServiceTest.java
  leeedohyun/src/test/java/inflearn/mini/api/AnnualLeaveApiTest.java
  leeedohyun/src/test/java/inflearn/mini/api/CommuteApiTest.java
  leeedohyun/src/test/java/inflearn/mini/api/DatabaseCleanUp.java
  leeedohyun/src/test/java/inflearn/mini/api/EmployeeApiTest.java
  leeedohyun/src/test/java/inflearn/mini/api/steps/AnnualLeaveSteps.java
  leeedohyun/src/test/java/inflearn/mini/api/steps/CommuteSteps.java
  leeedohyun/src/test/java/inflearn/mini/api/steps/EmployeeSteps.java
  leeedohyun/src/test/java/inflearn/mini/commute/controller/CommuteControllerTest.java
  leeedohyun/src/test/java/inflearn/mini/commute/domain/CommuteTest.java
  leeedohyun/src/test/java/inflearn/mini/commute/service/CommuteServiceTest.java
  leeedohyun/src/test/java/inflearn/mini/employee/controller/EmployeeControllerTest.java
  leeedohyun/src/test/java/inflearn/mini/employee/domain/EmployeeTest.java
  leeedohyun/src/test/java/inflearn/mini/employee/service/EmployeeServiceTest.java
  leeedohyun/src/test/java/inflearn/mini/team/controller/TeamControllerTest.java
  leeedohyun/src/test/java/inflearn/mini/team/domain/TeamTest.java
  leeedohyun/src/test/java/inflearn/mini/team/service/TeamServiceTest.java
Labels: 3️⃣ 3단계
